doc.type.html
script
filename=covid strings27 key words.js
covid strings27 key word list=[self regulation,covid antibodies,side effect covid immune response,self care,covid fatigue syndrome escape,long covid,100-61,lab leak credibility,fatigue syndrome more attention,covid test line,symptoms,covid amount come out as,careful taking medications,changing covid positions]
string=””
for string in covid strings search word list
select characters
edit diffuse property
desired color=green
covid strings27 reference list=[a:long covid patients report improvements following self-regulation therapy,study finds (msn.com),b:covid-19 antibody discovery could explain long covid(msn.com),c:covid toes:symptoms,causes,treatment (health.com),d:what is self-care and why is it important? (verywellhealth.com),e:new research supports an annual covid vaccine plan (msn.com),f:rob thomas -small town christmas lyrics |azlyrics.com,g:is long covid really chronic fatigue syndrome by another name? |columbia university mailman school of public health,h:what doctors wish patients knew about pandemic fatigue |american medical association (ama-assn.org),
i:long covid has forced the u.s. to take chronic fatigue syndrome seriously-the atlantic,j:fauci admits to covid-19 failures,says lab leak is credible (msn.com),k:chronic fatigue offers clues to long covid(msn.com),l:what does a faint line on a rapid covid-19 test mean? (msn.com),m:what is the order of covid symptoms this fall? (verywellhealth.com),n:2024 mercedes-benz glc-class review,pricing,and specs (caranddriver.com),o:the latest covid guidance:symptoms,treatment and more -the new york times (nytimes.com),p:vivek ramaswamy has changed his position on trump, covid vaccines (cincinnati.com)]
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
a=pc.create script(a);
a.attributes.add(foobar,{type:entity});
a.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
b=pc.create script(b);
b.attributes.add(foobar,{type:entity});
b.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
c=pc.create script(c);
c.attributes.add(foobar,{type:entity});
c.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
c=pc.create script(c);
c.attributes.add(foobar,{type:entity});
c.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
d=pc.create script(d);
d.attributes.add(foobar,{type:entity});
d.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
e=pc.create script(e);
e.attributes.add(foobar,{type:entity});
e.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
f=pc.create script(f);
f.attributes.add(foobar,{type:entity});
f.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
g=pc.create script(g);
g.attributes.add(foobar,{type:entity});
g.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
h=pc.create script(h);
h.attributes.add(foobar,{type:entity});
h.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
i=pc.create script(i);
i.attributes.add(foobar,{type:entity});
i.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
j=pc.create script(j);
j.attributes.add(foobar,{type:entity});
j.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
k=pc.create script(k);
k.attributes.add(foobar,{type:entity});
k.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
m=pc.create script(m);
m.attributes.add(foobar,{type:entity});
m.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
n=pc.create script(n);
n.attributes.add(foobar,{type:entity});
n.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
o=pc.create script(o);
o.attributes.add(foobar,{type:entity});
o.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instanite
entity script foobar=this entity
entity reparnet (this.entity)
p=pc.create script(p);
p.attributes.add(foobar,{type:entity});
p.prototype.initialize=function() 
console.log(this.foobar.name);
return filename
