doc.type.html
script
filename=covid strings27 key words.js
covid strings27 key word list=[self regulation,covid antibodies,side effect covid immune response,self care,covid fatigue syndrome escape,long covid,100-61,lab leak credibility,fatigue syndrome more attention,covid test line,symptoms,covid amount come out as,careful taking medications,changing covid positions]
string=””
for string in covid strings search word list
select characters
edit diffuse property
desired color=green
covid strings27 reference list=[a:long covid patients report improvements following self-regulation therapy,study finds (msn.com),b:covid-19 antibody discovery could explain long covid(msn.com),c:covid toes:symptoms,causes,treatment (health.com),d:what is self-care and why is it important? (verywellhealth.com),e:new research supports an annual covid vaccine plan (msn.com),f:rob thomas -small town christmas lyrics |azlyrics.com,g:is long covid really chronic fatigue syndrome by another name? |columbia university mailman school of public health,h:what doctors wish patients knew about pandemic fatigue |american medical association (ama-assn.org),
i:long covid has forced the u.s. to take chronic fatigue syndrome seriously-the atlantic,j:fauci admits to covid-19 failures,says lab leak is credible (msn.com),k:chronic fatigue offers clues to long covid(msn.com),l:what does a faint line on a rapid covid-19 test mean? (msn.com),m:what is the order of covid symptoms this fall? (verywellhealth.com),n:2024 mercedes-benz glc-class review,pricing,and specs (caranddriver.com),o:the latest covid guidance:symptoms,treatment and more -the new york times (nytimes.com),p:vivek ramaswamy has changed his position on trump, covid vaccines (cincinnati.com)]
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
a=pc.create script(a);
a.attributes.add(foobar,{type:entity});
a.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
b=pc.create script(b);
b.attributes.add(foobar,{type:entity});
b.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
c=pc.create script(c);
c.attributes.add(foobar,{type:entity});
c.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
c=pc.create script(c);
c.attributes.add(foobar,{type:entity});
c.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
d=pc.create script(d);
d.attributes.add(foobar,{type:entity});
d.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
e=pc.create script(e);
e.Attributes.Add(Foobar,{Type:Entity});
e.Prototype.Initialize =Function() 
Console.Log(This.Foobar.Name);
Asset=This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar=This Entity
Entity Reparnet (This.Entity)
F=Pc.CreateScript(F);
F.Attributes.Add(Foobar,{Type:Entity});
F.Prototype.Initialize =Function() 
Console.Log(This.Foobar.Name);
Asset=This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar=This Entity
Entity Reparnet (This.Entity)
G=Pc.CreateScript(G);
G.Attributes.Add(Foobar,{Type:Entity});
G.Prototype.Initialize =Function() 
Console.Log(This.Foobar.Name);
Asset=This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar=This Entity
Entity Reparnet (This.Entity)
H=Pc.CreateScript(H);
H.Attributes.Add(Foobar,{Type:Entity});
H.Prototype.Initialize =Function() 
Console.Log(This.Foobar.Name);
Asset=This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar=This Entity
Entity Reparnet (This.Entity)
I=Pc.CreateScript(I);
I.Attributes.Add(Foobar,{Type:Entity});
I.Prototype.Initialize =Function() 
Console.Log(This.Foobar.Name);
Asset=This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar=This Entity
Entity Reparnet (This.Entity)
J=Pc.CreateScript(J);
J.Attributes.Add(Foobar,{Type:Entity});
J.Prototype.Initialize =Function() 
Console.Log(This.Foobar.Name);
Asset=This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar=This Entity
Entity Reparnet (This.Entity)
K=Pc.CreateScript(K);
K.Attributes.Add(Foobar,{Type:Entity});
K.Prototype.Initialize =Function() 
Console.Log(This.Foobar.Name);
Asset=This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar=This Entity
Entity Reparnet (This.Entity)
M=Pc.CreateScript(M);
M.Attributes.Add(Foobar,{Type:Entity});
M.Prototype.Initialize =Function() 
Console.Log(This.Foobar.Name);
Asset=This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar=This Entity
Entity Reparnet (This.Entity)
N=Pc.CreateScript(N);
N.Attributes.Add(Foobar,{Type:Entity});
N.Prototype.Initialize =Function() 
Console.Log(This.Foobar.Name);
Asset=This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar=This Entity
Entity Reparnet (This.Entity)
O=Pc.CreateScript(O);
O.Attributes.Add(Foobar,{Type:Entity});
O.Prototype.Initialize =Function() 
Console.Log(This.Foobar.Name);
Asset=This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar=This Entity
Entity Reparnet (This.Entity)
P=Pc.CreateScript(P);
P.Attributes.Add(Foobar,{Type:Entity});
P.Prototype.Initialize =Function() 
Console.Log(This.Foobar.Name);
return filename
